experiment: 
  type: experiment/online_learning
  runs: 1
  run_offset: 0
  trials: 0
  steps: 100000
  rate: 0
  test_interval: 10
  output: agent_cp_tau_replay_ddpg_tensorflow_sincos_i10_j0
  save_every: run

  agent:
    type: agent/replay
    memory_size: 100000
    replay_steps: 128
    batch_size: 64
    observation_steps: 1000
    threads: 0
    policy:
      type: mapping/policy/action
      sigma: [1.0]
      theta: [0.15]
      decay_rate: 1
      decay_min: 0
      renormalize: 1
      output_min: experiment/environment/task/action_min
      output_max: experiment/environment/task/action_max
      projector:
        type: projector/pre/normalizing
        signed: 0
        input_min: experiment/environment/task/observation_min
        input_max: experiment/environment/task/observation_max
        projector:
          type: projector/pre/geometric
          angles: [0, 1, 0, 0]
          normalized: 1
          projector:
            type: projector/identity
      representation:
        type: representation/parameterized/tensorflow
        memory: 0.2
        interval: 100
        tau: 0.01
        file: ../cfg/network/4layer_tanh_ddpg.py ../../projector/projector/memory experiment/environment/task/action_dims 0.0001 0.001 "relu" "linear" 400 300
        input_layer: s_in, a_in
        output_layer: a_out/Tanh
        init_node: init
        update_node: update
        file_suffix: my_policy10_0
      value:
        type: mapping/represented
        projector: experiment/agent/policy/projector
        representation: experiment/agent/policy/representation
      output_min: experiment/environment/task/action_min
      output_max: experiment/environment/task/action_max
    predictor:
      type: predictor/ddpg
      gamma: 0.98
      reward_scale: 1
      observation: s_in
      action: a_in
      value: q/BiasAdd
      target: target
      critic_update: update
      actor_update: a_update
      discretizer: 0
      obs_projector: experiment/agent/policy/projector
      action_projector:
        type: projector/pre/normalizing
        signed: 1
        input_min: experiment/agent/policy/output_min
        input_max: experiment/agent/policy/output_max
        projector:
          type: projector/identity
      representation: experiment/agent/policy/representation
  test_agent:
    type: agent/fixed
    policy:
      type: mapping/policy/action
      sigma: []
      theta: []
      decay_rate: 1
      decay_min: 0
      renormalize: 1
      output_min: experiment/agent/policy/output_min
      output_max: experiment/agent/policy/output_max
      projector: experiment/agent/policy/projector
      representation: experiment/agent/policy/representation
      value:
        - experiment/agent/policy/value
      output_min: experiment/environment/task/action_min
      output_max: experiment/environment/task/action_max